

GET http://localhost:3000/v1/note/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYXNodXRvc2hwIiwiaWF0IjoxNzQyMjI4OTU3LCJleHAiOjE3NDIzMTUzNTd9.CLy_Srzl4qon7MgQsboGURAPiwY6tFqvKJ2LpAUCV40